// LOCAL DEVELOPMENT ONLY: derive anon/service_role JWTs from the local JWT
// secret and write .env.local. Never use these values outside localhost.
import crypto from 'node:crypto';
import fs from 'node:fs';

const secret = process.env.LOCAL_JWT_SECRET ?? 'super-secret-jwt-token-with-at-least-32-characters-long';
const b64 = (o) => Buffer.from(JSON.stringify(o)).toString('base64url');
const sign = (payload) => {
  const head = b64({ alg: 'HS256', typ: 'JWT' });
  const body = b64(payload);
  const sig = crypto.createHmac('sha256', secret).update(`${head}.${body}`).digest('base64url');
  return `${head}.${body}.${sig}`;
};
const iat = Math.floor(Date.now() / 1000);
const exp = iat + 10 * 365 * 24 * 3600;
const anon = sign({ iss: 'supabase-local', role: 'anon', iat, exp });
const service = sign({ iss: 'supabase-local', role: 'service_role', iat, exp });

const env = `# LOCAL DEVELOPMENT ONLY — generated by scripts/local/keys.mjs
SUPABASE_URL=http://127.0.0.1:54321
SUPABASE_ANON_KEY=${anon}
SUPABASE_SERVICE_ROLE_KEY=${service}
APP_URL=http://localhost:3000
LOCAL_DB_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres
DEMO_PASSWORD=demo-password-123
CRON_SECRET=local-cron-secret-0123456789abcdef
`;
fs.writeFileSync(new URL('../../.env.local', import.meta.url), env);
console.log('wrote .env.local');
